import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Realisateur generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Realisateur implements java.io.Serializable {
	private static final long serialVersionUID = 3742599827373516148L;
	
	private int noRea;
	private String nomRea;
	private String prenRea;
	@XmlTransient
	private Set<Film> films = new HashSet<Film>(0);

	public Realisateur() {}

	public Realisateur(int noRea, String nomRea, String prenRea) {
		this.noRea = noRea;
		this.nomRea = nomRea;
		this.prenRea = prenRea;
	}

	public Realisateur(int noRea, String nomRea, String prenRea, Set<Film> films) {
		this.noRea = noRea;
		this.nomRea = nomRea;
		this.prenRea = prenRea;
		this.films = films;
	}
	
	public int getNoRea() {
		return this.noRea;
	}

	public void setNoRea(int noRea) {
		this.noRea = noRea;
	}

	public String getNomRea() {
		return this.nomRea;
	}

	public void setNomRea(String nomRea) {
		this.nomRea = nomRea;
	}

	public String getPrenRea() {
		return this.prenRea;
	}

	public void setPrenRea(String prenRea) {
		this.prenRea = prenRea;
	}

	public Set<Film> getFilms() {
		return this.films;
	}

	public void setFilms(Set<Film> films) {
		this.films = films;
	}

}
