package main.java.com.epul.metier;
// Generated 10 oct. 2016 23:12:09 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Categorie generated by hbm2java
 */
public class Categorie implements java.io.Serializable {

	private String codeCat;
	private String libelleCat;
	private Set films = new HashSet(0);

	public Categorie() {
	}

	public Categorie(String codeCat, String libelleCat) {
		this.codeCat = codeCat;
		this.libelleCat = libelleCat;
	}

	public Categorie(String codeCat, String libelleCat, Set films) {
		this.codeCat = codeCat;
		this.libelleCat = libelleCat;
		this.films = films;
	}

	public String getCodeCat() {
		return this.codeCat;
	}

	public void setCodeCat(String codeCat) {
		this.codeCat = codeCat;
	}

	public String getLibelleCat() {
		return this.libelleCat;
	}

	public void setLibelleCat(String libelleCat) {
		this.libelleCat = libelleCat;
	}

	public Set getFilms() {
		return this.films;
	}

	public void setFilms(Set films) {
		this.films = films;
	}

}
