package main.java.com.epul.metier;
// Generated 10 oct. 2016 23:12:09 by Hibernate Tools 4.0.0

/**
 * Personnage generated by hbm2java
 */
public class Personnage implements java.io.Serializable {

	private PersonnageId id;
	private Acteur acteur;
	private Film film;
	private String nomPers;

	public Personnage() {
	}

	public Personnage(PersonnageId id, Acteur acteur, Film film, String nomPers) {
		this.id = id;
		this.acteur = acteur;
		this.film = film;
		this.nomPers = nomPers;
	}

	public PersonnageId getId() {
		return this.id;
	}

	public void setId(PersonnageId id) {
		this.id = id;
	}

	public Acteur getActeur() {
		return this.acteur;
	}

	public void setActeur(Acteur acteur) {
		this.acteur = acteur;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public String getNomPers() {
		return this.nomPers;
	}

	public void setNomPers(String nomPers) {
		this.nomPers = nomPers;
	}

}
