package main.java.com.epul.metier;
// Generated 25 oct. 2016 08:43:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Personnage generated by hbm2java
 */
@Entity
@Table(name = "personnage", catalog = "cinema")
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Personnage implements java.io.Serializable {
	private static final long serialVersionUID = 6735270888573150495L;
	
	@EmbeddedId
	@AttributeOverrides({ 
		@AttributeOverride(name = "noFilm", column = @Column(name = "NoFilm", nullable = false)),
		@AttributeOverride(name = "noAct", column = @Column(name = "NoAct", nullable = false)) 
	})
	private PersonnageId id;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "NoAct", nullable = false, insertable = false, updatable = false)
	private Acteur acteur;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "NoFilm", nullable = false, insertable = false, updatable = false)
	private Film film;
	@Column(name = "NomPers", nullable = false, length = 30)
	private String nomPers;

	public Personnage() {
	}

	public Personnage(PersonnageId id, Acteur acteur, Film film, String nomPers) {
		this.id = id;
		this.acteur = acteur;
		this.film = film;
		this.nomPers = nomPers;
	}

	
	public PersonnageId getId() {
		return this.id;
	}

	public void setId(PersonnageId id) {
		this.id = id;
	}

	public Acteur getActeur() {
		return this.acteur;
	}

	public void setActeur(Acteur acteur) {
		this.acteur = acteur;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public String getNomPers() {
		return this.nomPers;
	}

	public void setNomPers(String nomPers) {
		this.nomPers = nomPers;
	}

}
