package main.java.com.epul.metier;
// Generated 25 oct. 2016 08:43:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Realisateur generated by hbm2java
 */
@Entity
@Table(name = "realisateur", catalog = "cinema")
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Realisateur implements java.io.Serializable {
	private static final long serialVersionUID = 3742599827373516148L;
	
	private int noRea;
	private String nomRea;
	private String prenRea;
	@XmlTransient
	private Set<Film> films = new HashSet<Film>(0);

	public Realisateur() {
	}

	public Realisateur(int noRea, String nomRea, String prenRea) {
		this.noRea = noRea;
		this.nomRea = nomRea;
		this.prenRea = prenRea;
	}

	public Realisateur(int noRea, String nomRea, String prenRea, Set<Film> films) {
		this.noRea = noRea;
		this.nomRea = nomRea;
		this.prenRea = prenRea;
		this.films = films;
	}

	@Id

	@Column(name = "NoRea", unique = true, nullable = false)
	public int getNoRea() {
		return this.noRea;
	}

	public void setNoRea(int noRea) {
		this.noRea = noRea;
	}

	@Column(name = "NomRea", nullable = false, length = 20)
	public String getNomRea() {
		return this.nomRea;
	}

	public void setNomRea(String nomRea) {
		this.nomRea = nomRea;
	}

	@Column(name = "PrenRea", nullable = false, length = 20)
	public String getPrenRea() {
		return this.prenRea;
	}

	public void setPrenRea(String prenRea) {
		this.prenRea = prenRea;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "realisateur")
	public Set<Film> getFilms() {
		return this.films;
	}

	public void setFilms(Set<Film> films) {
		this.films = films;
	}

}
