package main.resources;

// default package
// Generated 10 oct. 2016 11:51:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Acteur generated by hbm2java
 */
public class Acteur implements java.io.Serializable {

	private int noAct;
	private String nomAct;
	private String prenAct;
	private Date dateNaiss;
	private Date dateDeces;
	private Set personnages = new HashSet(0);

	public Acteur() {
	}

	public Acteur(int noAct, String nomAct) {
		this.noAct = noAct;
		this.nomAct = nomAct;
	}

	public Acteur(int noAct, String nomAct, String prenAct, Date dateNaiss, Date dateDeces, Set personnages) {
		this.noAct = noAct;
		this.nomAct = nomAct;
		this.prenAct = prenAct;
		this.dateNaiss = dateNaiss;
		this.dateDeces = dateDeces;
		this.personnages = personnages;
	}

	public int getNoAct() {
		return this.noAct;
	}

	public void setNoAct(int noAct) {
		this.noAct = noAct;
	}

	public String getNomAct() {
		return this.nomAct;
	}

	public void setNomAct(String nomAct) {
		this.nomAct = nomAct;
	}

	public String getPrenAct() {
		return this.prenAct;
	}

	public void setPrenAct(String prenAct) {
		this.prenAct = prenAct;
	}

	public Date getDateNaiss() {
		return this.dateNaiss;
	}

	public void setDateNaiss(Date dateNaiss) {
		this.dateNaiss = dateNaiss;
	}

	public Date getDateDeces() {
		return this.dateDeces;
	}

	public void setDateDeces(Date dateDeces) {
		this.dateDeces = dateDeces;
	}

	public Set getPersonnages() {
		return this.personnages;
	}

	public void setPersonnages(Set personnages) {
		this.personnages = personnages;
	}

}
