// default package
// Generated 10 oct. 2016 11:51:27 by Hibernate Tools 3.4.0.CR1

/**
 * PersonnageId generated by hbm2java
 */
public class PersonnageId implements java.io.Serializable {

	private int noFilm;
	private int noAct;

	public PersonnageId() {
	}

	public PersonnageId(int noFilm, int noAct) {
		this.noFilm = noFilm;
		this.noAct = noAct;
	}

	public int getNoFilm() {
		return this.noFilm;
	}

	public void setNoFilm(int noFilm) {
		this.noFilm = noFilm;
	}

	public int getNoAct() {
		return this.noAct;
	}

	public void setNoAct(int noAct) {
		this.noAct = noAct;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonnageId))
			return false;
		PersonnageId castOther = (PersonnageId) other;

		return (this.getNoFilm() == castOther.getNoFilm()) && (this.getNoAct() == castOther.getNoAct());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNoFilm();
		result = 37 * result + this.getNoAct();
		return result;
	}

}
