package main.resources.com.epul.metier;
// Generated 10 oct. 2016 23:12:09 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Realisateur generated by hbm2java
 */
public class Realisateur implements java.io.Serializable {

	private int noRea;
	private String nomRea;
	private String prenRea;
	private Set films = new HashSet(0);

	public Realisateur() {
	}

	public Realisateur(int noRea, String nomRea, String prenRea) {
		this.noRea = noRea;
		this.nomRea = nomRea;
		this.prenRea = prenRea;
	}

	public Realisateur(int noRea, String nomRea, String prenRea, Set films) {
		this.noRea = noRea;
		this.nomRea = nomRea;
		this.prenRea = prenRea;
		this.films = films;
	}

	public int getNoRea() {
		return this.noRea;
	}

	public void setNoRea(int noRea) {
		this.noRea = noRea;
	}

	public String getNomRea() {
		return this.nomRea;
	}

	public void setNomRea(String nomRea) {
		this.nomRea = nomRea;
	}

	public String getPrenRea() {
		return this.prenRea;
	}

	public void setPrenRea(String prenRea) {
		this.prenRea = prenRea;
	}

	public Set getFilms() {
		return this.films;
	}

	public void setFilms(Set films) {
		this.films = films;
	}

}
